/**
 * @file settings_persist.h
 * @author auto-generated
 * @brief Settings_persist模块的头文件
 * @version 0.1
 * @date 2025-11-06 15:26:40
 *
 * @attention This file is auto-generated by generate_settings_from_ini.py. Do not edit manually!
 * @copyright Copyright (c) 2025
 *
 */
#ifndef _SETTINGS_PERSIST_H
#define _SETTINGS_PERSIST_H

#include <stdbool.h>
#include <stdint.h>
#include <string.h>

typedef struct
{
    /* Audio settings */
    struct
    {
        int volume;  /* default: 75, min: 0, max: 100 */
        bool mute;  /* default: false */
    } Audio;

    /* Display settings */
    struct
    {
        int brightness;  /* default: 60, min: 0, max: 100 */
        char screensaver[8];  /* default: "enabled" */
    } Display;

    /* Verify settings */
    struct
    {
        int crc_16_ibm;  /* default: 0, min: 0, max: 65535 */
    } Verify;

} Settings;

int settings_persist_init(void);

int settings_persist_get_data(Settings *settings);

int settings_persist_set_data(const Settings *settings);

int settings_persist_reset_all_data(void);

int settings_persist_set_Audio_volume(int volume);

int settings_persist_set_Audio_mute(bool mute);

int settings_persist_set_Display_brightness(int brightness);

int settings_persist_set_Display_screensaver(const char* screensaver);

int settings_persist_deinit(void);

#endif /* _SETTINGS_PERSIST_H */
